// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgcrwdctmbtxgmooxfqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnY3J3ZGN0bWJ0eGdtb294ZnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTU2MjIsImV4cCI6MjA2NTU5MTYyMn0.F96ZI9XRJlPGxaMzikCv1ODnkEriHugSSXGq51RD1ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});